title = "Xiang's First Blog"
publishDir = "docs"
baseURL = "https://winsa24.github.io"
languageCode = "en-us"
theme = "dream"


[params]
  # background = "black"
  backgroundImage = "/static/images/ipp.jpg"
  linkColor = "seagreen"

  author = "Xiang WEI"
  # description = ""
  avatar = "/img/avatar.jpg"
  motto = "Vouloir, c'est pouvoir"
  # categoriesLimitInHeader = 6
  # headerBottomText = ""

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  
  email = "xiang.wei@telecom-paris.fr"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
